spring:
  profiles:
    active: production

  data:
    elasticsearch:
      repositories:
        enabled: false

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      pool-name: bloqly-db-pool
      auto-commit: false
      transaction-isolation: TRANSACTION_READ_COMMITTED
    url: jdbc:postgresql:${database.name}
    username: ${database.username}
    password: ${database.password}

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

server:
  port: ${port}
  undertow:
    max-http-post-size: 1048576 # 1MiB